apiVersion: v1 
kind: PersistentVolume
metadata: 
  name: pv-nginx
  labels: 
    log: nginx
spec: 
  storageClassName: manual
  capacity: 
    storage: 500Mi
  accessModes: 
  - ReadWriteOnce
  hostPath: 
    path: /usr/local/data
    type: DirectoryOrCreate
