apiVersion: v1 
kind: Pod
metadata:
  name: cmd-args-pod
  labels: 
    app: backend
spec: 
  containers:
  - name: cont-name-cmd-args
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "echo Hello behen ke lawde && sleep 36000"]
  restartPolicy: Never

