apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: memory-hpa
spec: 
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa
  metrics: 
  - type: Resource
    resource: 
      name: memory
      target: 
        type: Utilization
        averageUtilization: 50
