apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: cpu-memory-hpa
spec: 
  minReplicas: 1 
  maxReplicas: 10
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-hpa
  metrics: 
   - type: Resource
     resource: 
       name: cpu 
       target: 
         type: Utilization 
         averageUtilization: 20
   - type: Resource
     resource: 
       name: memory
       target:       
         type: Utilization 
         averageUtilization: 20 
  behavior: 
    scaleDown: 
      stabilizationWindowSeconds: 300
      policies: 
      - type: Percent
        value: 20
        periodSeconds: 60
